//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatingChart
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakModel
    {
        public int BreakId { get; set; }
        public int Employee { get; set; }
        public System.DateTime TimeEntered { get; set; }
        public Nullable<System.DateTime> TimeCleared { get; set; }
    
        public virtual EmployeeModel EmployeeModel { get; set; }
    }
}
